alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/hostname: fedora
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: local-path
  service:
    type: NodePort
    nodePort: 30109

grafana:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: fedora
  grafana.ini:
    metrics:
      enabled: true
  initChownData:
    enabled: false
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 10Gi
    storageClassName: local-path
  replicas: 1
  service:
    type: NodePort
    nodePort: 30105
    port: 80
    portName: http-web
    targetPort: 3000
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
    path: /metrics
    scheme: http
    scrapeTimeout: 30s

prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/hostname: fedora
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: local-path
    additionalScrapeConfigs:
      - job_name: 'webrtc'
        scrape_interval: 15s
        scheme: https
        static_configs:
          - targets: ['10.0.0.11:5000']
            labels:
              app_environment: 'external-vm'
              app_name: 'WebRTC'
        tls_config:
          insecure_skip_verify: true
      - job_name: 'spiritist-books-backend'
        scrape_interval: 15s
        scheme: http
        static_configs:
          - targets: ['10.0.0.11:3000']
            labels:
              app_environment: 'external-vm'
              app_name: 'Spiritist-Books-Backend'
  service:
    type: NodePort
    nodePort: 30108
