apiVersion: apps/v1
kind: Deployment

metadata:
  name: e-commerce-api
  namespace: e-commerce-api

  labels:
    app: e-commerce-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: e-commerce-api

  template:
    metadata:
      labels:
        app: e-commerce-api

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - e-commerce-api
              topologyKey: kubernetes.io/hostname
      containers:
      - name: e-commerce-api
        image: scudella/e-commerce-api:v1.1.2
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5000

        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: MONGO_URI
              name: app-credentials-e-commerce-api

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: app-credentials-e-commerce-api

        - name: JWT_LIFETIME
          value: 1d
