apiVersion: v1
kind: Service

metadata:
  name: jobs-api
  namespace: jobs-api

  labels:
    app: jobs-api

spec:
  ports:
  - port: 5000
    targetPort: 5000

  selector:
    app: jobs-api

  type: ClusterIP
