apiVersion: v1
kind: ConfigMap
  
metadata:
  name: config
  namespace: store-nextjs
  labels:
    app: store-nextjs

data:
  OCI_REGION: us-ashburn-1
  OCI_BUCKET: bucket-store-nextjs
  NEXT_PUBLIC_WEBSITE_URL: https://store-nextjs.scudella.net.br
  ORIGIN: https://store-nextjs.scudella.net.br
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_51JdefnIbmqmaq4JHC2CAifJhMd9HZSdbA10um8YC7K66VBV7q3iu4TVHKvcEGSDtStEeba0VkLgpNWgs6Ee5llPz00jQYQVT1H
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_dHJ1ZS1tdWxsZXQtMTYuY2xlcmsuYWNjb3VudHMuZGV2JA
  OCI_PRIVATE_KEY_PATH: /etc/secrets/oci/oci_api_key.pem
