apiVersion: v1
kind: Secret

metadata:
  name: app-credentials-store-nextjs
  namespace: store-nextjs

type: Opaque

stringData:
  DATABASE_URL: "<replace>"
  CLERK_SECRET_KEY: "<replace>"
  ADMIN_USER_ID: "<replace>"
  OCI_TENANCY_OCID: "<replace>"
  OCI_USER_OCID: "<replace>"
  OCI_FINGERPRINT: "<replace>"
  STRIPE_SECRET_KEY: "<replace>"
